### ISSUE TITLE
failing tests on CI

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/fast-date#1]
as titled

**Comment by davidmarkclements** [comment]
This is to do with dependencies (nyc) failing on node 0.10 and 0.12 - can probably just drop support for these libraries

**Comment by davidmarkclements** [comment]
Not libraries - node versions

**Comment by mcollina** [comment]
Definitely drop support for 0.10 and 0.12.

**Comment by davidmarkclements** [comment]
fixed
